const CURATED_DRUGS = {
  'препарат 1': {
    name: 'Амоксициллин',
    activeSubstance: 'Амоксициллин',
    group: 'Антибиотик',
    thumbnailUrl: '/assets/img/drugs/packshots/amoxicillin.svg',
    images: ['/assets/img/drugs/packshots/amoxicillin.svg', '/assets/img/drugs/pack-01.svg'],
  },
  'амоксициллин': {
    name: 'Амоксициллин',
    activeSubstance: 'Амоксициллин',
    group: 'Антибиотик',
    thumbnailUrl: '/assets/img/drugs/packshots/amoxicillin.svg',
    images: ['/assets/img/drugs/packshots/amoxicillin.svg', '/assets/img/drugs/pack-01.svg'],
  },
  'препарат 2': {
    name: 'Мелоксикам',
    activeSubstance: 'Мелоксикам',
    group: 'НПВС',
    thumbnailUrl: '/assets/img/drugs/packshots/meloxicam.svg',
    images: ['/assets/img/drugs/packshots/meloxicam.svg', '/assets/img/drugs/pack-02.svg'],
  },
  'мелоксикам': {
    name: 'Мелоксикам',
    activeSubstance: 'Мелоксикам',
    group: 'НПВС',
    thumbnailUrl: '/assets/img/drugs/packshots/meloxicam.svg',
    images: ['/assets/img/drugs/packshots/meloxicam.svg', '/assets/img/drugs/pack-02.svg'],
  },
  'препарат 3': {
    name: 'Маропитант',
    activeSubstance: 'Маропитант',
    group: 'Противорвотный',
    thumbnailUrl: '/assets/img/drugs/packshots/maropitant.svg',
    images: ['/assets/img/drugs/packshots/maropitant.svg', '/assets/img/drugs/pack-03.svg'],
  },
  'маропитант': {
    name: 'Маропитант',
    activeSubstance: 'Маропитант',
    group: 'Противорвотный',
    thumbnailUrl: '/assets/img/drugs/packshots/maropitant.svg',
    images: ['/assets/img/drugs/packshots/maropitant.svg', '/assets/img/drugs/pack-03.svg'],
  },
  'препарат 4': {
    name: 'Преднизолон',
    activeSubstance: 'Преднизолон',
    group: 'Глюкокортикостероид',
    thumbnailUrl: '/assets/img/drugs/packshots/prednisolone.svg',
    images: ['/assets/img/drugs/packshots/prednisolone.svg', '/assets/img/drugs/pack-04.svg'],
  },
  'преднизолон': {
    name: 'Преднизолон',
    activeSubstance: 'Преднизолон',
    group: 'Глюкокортикостероид',
    thumbnailUrl: '/assets/img/drugs/packshots/prednisolone.svg',
    images: ['/assets/img/drugs/packshots/prednisolone.svg', '/assets/img/drugs/pack-04.svg'],
  },
  'препарат 5': {
    name: 'Фуросемид',
    activeSubstance: 'Фуросемид',
    group: 'Диуретик',
    thumbnailUrl: '/assets/img/drugs/packshots/furosemide.svg',
    images: ['/assets/img/drugs/packshots/furosemide.svg', '/assets/img/drugs/pack-05.svg'],
  },
  'фуросемид': {
    name: 'Фуросемид',
    activeSubstance: 'Фуросемид',
    group: 'Диуретик',
    thumbnailUrl: '/assets/img/drugs/packshots/furosemide.svg',
    images: ['/assets/img/drugs/packshots/furosemide.svg', '/assets/img/drugs/pack-05.svg'],
  },
  'препарат 6': {
    name: 'Омепразол',
    activeSubstance: 'Омепразол',
    group: 'Гастропротектор',
    thumbnailUrl: '/assets/img/drugs/packshots/omeprazole.svg',
    images: ['/assets/img/drugs/packshots/omeprazole.svg', '/assets/img/drugs/pack-06.svg'],
  },
  'омепразол': {
    name: 'Омепразол',
    activeSubstance: 'Омепразол',
    group: 'Гастропротектор',
    thumbnailUrl: '/assets/img/drugs/packshots/omeprazole.svg',
    images: ['/assets/img/drugs/packshots/omeprazole.svg', '/assets/img/drugs/pack-06.svg'],
  },
  'препарат 7': {
    name: 'Габапентин',
    activeSubstance: 'Габапентин',
    group: 'Нейромодулятор',
    thumbnailUrl: '/assets/img/drugs/packshots/gabapentin.svg',
    images: ['/assets/img/drugs/packshots/gabapentin.svg', '/assets/img/drugs/pack-07.svg'],
  },
  'габапентин': {
    name: 'Габапентин',
    activeSubstance: 'Габапентин',
    group: 'Нейромодулятор',
    thumbnailUrl: '/assets/img/drugs/packshots/gabapentin.svg',
    images: ['/assets/img/drugs/packshots/gabapentin.svg', '/assets/img/drugs/pack-07.svg'],
  },
  'препарат 8': {
    name: 'Доксициклин',
    activeSubstance: 'Доксициклин',
    group: 'Антибиотик',
    thumbnailUrl: '/assets/img/drugs/packshots/doxycycline.svg',
    images: ['/assets/img/drugs/packshots/doxycycline.svg', '/assets/img/drugs/pack-08.svg'],
  },
  'доксициклин': {
    name: 'Доксициклин',
    activeSubstance: 'Доксициклин',
    group: 'Антибиотик',
    thumbnailUrl: '/assets/img/drugs/packshots/doxycycline.svg',
    images: ['/assets/img/drugs/packshots/doxycycline.svg', '/assets/img/drugs/pack-08.svg'],
  },
  'препарат 9': {
    name: 'Сукральфат',
    activeSubstance: 'Сукральфат',
    group: 'Гастропротектор',
    thumbnailUrl: '/assets/img/drugs/packshots/sucralfate.svg',
    images: ['/assets/img/drugs/packshots/sucralfate.svg', '/assets/img/drugs/pack-09.svg'],
  },
  'сукральфат': {
    name: 'Сукральфат',
    activeSubstance: 'Сукральфат',
    group: 'Гастропротектор',
    thumbnailUrl: '/assets/img/drugs/packshots/sucralfate.svg',
    images: ['/assets/img/drugs/packshots/sucralfate.svg', '/assets/img/drugs/pack-09.svg'],
  },
  'препарат 10': {
    name: 'Леветирацетам',
    activeSubstance: 'Леветирацетам',
    group: 'Противосудорожный',
    thumbnailUrl: '/assets/img/drugs/packshots/levetiracetam.svg',
    images: ['/assets/img/drugs/packshots/levetiracetam.svg', '/assets/img/drugs/pack-10.svg'],
  },
  'леветирацетам': {
    name: 'Леветирацетам',
    activeSubstance: 'Леветирацетам',
    group: 'Противосудорожный',
    thumbnailUrl: '/assets/img/drugs/packshots/levetiracetam.svg',
    images: ['/assets/img/drugs/packshots/levetiracetam.svg', '/assets/img/drugs/pack-10.svg'],
  },
  'препарат 11': {
    name: 'Клопидогрел',
    activeSubstance: 'Клопидогрел',
    group: 'Кардиологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/clopidogrel.svg',
    images: ['/assets/img/drugs/packshots/clopidogrel.svg', '/assets/img/drugs/pack-11.svg'],
  },
  'клопидогрел': {
    name: 'Клопидогрел',
    activeSubstance: 'Клопидогрел',
    group: 'Кардиологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/clopidogrel.svg',
    images: ['/assets/img/drugs/packshots/clopidogrel.svg', '/assets/img/drugs/pack-11.svg'],
  },
  'препарат 12': {
    name: 'Адеметионин',
    activeSubstance: 'Адеметионин',
    group: 'Гепатопротектор',
    thumbnailUrl: '/assets/img/drugs/packshots/ademetionine.svg',
    images: ['/assets/img/drugs/packshots/ademetionine.svg', '/assets/img/drugs/pack-12.svg'],
  },
  'адеметионин': {
    name: 'Адеметионин',
    activeSubstance: 'Адеметионин',
    group: 'Гепатопротектор',
    thumbnailUrl: '/assets/img/drugs/packshots/ademetionine.svg',
    images: ['/assets/img/drugs/packshots/ademetionine.svg', '/assets/img/drugs/pack-12.svg'],
  },
  'препарат 13': {
    name: 'Пимобендан',
    activeSubstance: 'Пимобендан',
    group: 'Кардиологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/pimobendan.svg',
    images: ['/assets/img/drugs/packshots/pimobendan.svg', '/assets/img/drugs/pack-05.svg'],
  },
  'пимобендан': {
    name: 'Пимобендан',
    activeSubstance: 'Пимобендан',
    group: 'Кардиологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/pimobendan.svg',
    images: ['/assets/img/drugs/packshots/pimobendan.svg', '/assets/img/drugs/pack-05.svg'],
  },
  'препарат 14': {
    name: 'Энрофлоксацин',
    activeSubstance: 'Энрофлоксацин',
    group: 'Антибиотик',
    thumbnailUrl: '/assets/img/drugs/packshots/enrofloxacin.svg',
    images: ['/assets/img/drugs/packshots/enrofloxacin.svg', '/assets/img/drugs/pack-08.svg'],
  },
  'энрофлоксацин': {
    name: 'Энрофлоксацин',
    activeSubstance: 'Энрофлоксацин',
    group: 'Антибиотик',
    thumbnailUrl: '/assets/img/drugs/packshots/enrofloxacin.svg',
    images: ['/assets/img/drugs/packshots/enrofloxacin.svg', '/assets/img/drugs/pack-08.svg'],
  },
  'препарат 15': {
    name: 'Клиндамицин',
    activeSubstance: 'Клиндамицин',
    group: 'Антибиотик',
    thumbnailUrl: '/assets/img/drugs/packshots/clindamycin.svg',
    images: ['/assets/img/drugs/packshots/clindamycin.svg', '/assets/img/drugs/pack-09.svg'],
  },
  'клиндамицин': {
    name: 'Клиндамицин',
    activeSubstance: 'Клиндамицин',
    group: 'Антибиотик',
    thumbnailUrl: '/assets/img/drugs/packshots/clindamycin.svg',
    images: ['/assets/img/drugs/packshots/clindamycin.svg', '/assets/img/drugs/pack-09.svg'],
  },
  'препарат 16': {
    name: 'Миртазапин',
    activeSubstance: 'Миртазапин',
    group: 'Нейромодулятор',
    thumbnailUrl: '/assets/img/drugs/packshots/mirtazapine.svg',
    images: ['/assets/img/drugs/packshots/mirtazapine.svg', '/assets/img/drugs/pack-07.svg'],
  },
  'миртазапин': {
    name: 'Миртазапин',
    activeSubstance: 'Миртазапин',
    group: 'Нейромодулятор',
    thumbnailUrl: '/assets/img/drugs/packshots/mirtazapine.svg',
    images: ['/assets/img/drugs/packshots/mirtazapine.svg', '/assets/img/drugs/pack-07.svg'],
  },
  'препарат 17': {
    name: 'Лактулоза',
    activeSubstance: 'Лактулоза',
    group: 'Гастроэнтерология',
    thumbnailUrl: '/assets/img/drugs/packshots/lactulose.svg',
    images: ['/assets/img/drugs/packshots/lactulose.svg', '/assets/img/drugs/pack-06.svg'],
  },
  'лактулоза': {
    name: 'Лактулоза',
    activeSubstance: 'Лактулоза',
    group: 'Гастроэнтерология',
    thumbnailUrl: '/assets/img/drugs/packshots/lactulose.svg',
    images: ['/assets/img/drugs/packshots/lactulose.svg', '/assets/img/drugs/pack-06.svg'],
  },
  'препарат 18': {
    name: 'Беназеприл',
    activeSubstance: 'Беназеприл',
    group: 'Кардиологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/benazepril.svg',
    images: ['/assets/img/drugs/packshots/benazepril.svg', '/assets/img/drugs/pack-11.svg'],
  },
  'беназеприл': {
    name: 'Беназеприл',
    activeSubstance: 'Беназеприл',
    group: 'Кардиологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/benazepril.svg',
    images: ['/assets/img/drugs/packshots/benazepril.svg', '/assets/img/drugs/pack-11.svg'],
  },
  'препарат 19': {
    name: 'Карпрофен',
    activeSubstance: 'Карпрофен',
    group: 'НПВС',
    thumbnailUrl: '/assets/img/drugs/packshots/carprofen.svg',
    images: ['/assets/img/drugs/packshots/carprofen.svg', '/assets/img/drugs/pack-02.svg'],
  },
  'карпрофен': {
    name: 'Карпрофен',
    activeSubstance: 'Карпрофен',
    group: 'НПВС',
    thumbnailUrl: '/assets/img/drugs/packshots/carprofen.svg',
    images: ['/assets/img/drugs/packshots/carprofen.svg', '/assets/img/drugs/pack-02.svg'],
  },
  'препарат 20': {
    name: 'Метимазол',
    activeSubstance: 'Метимазол',
    group: 'Эндокринологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/methimazole.svg',
    images: ['/assets/img/drugs/packshots/methimazole.svg', '/assets/img/drugs/pack-04.svg'],
  },
  'метимазол': {
    name: 'Метимазол',
    activeSubstance: 'Метимазол',
    group: 'Эндокринологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/methimazole.svg',
    images: ['/assets/img/drugs/packshots/methimazole.svg', '/assets/img/drugs/pack-04.svg'],
  },
  'препарат 21': {
    name: 'Инсулин гларгин',
    activeSubstance: 'Инсулин гларгин',
    group: 'Эндокринологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/insulin-glargine.svg',
    images: ['/assets/img/drugs/packshots/insulin-glargine.svg', '/assets/img/drugs/pack-03.svg'],
  },
  'инсулин гларгин': {
    name: 'Инсулин гларгин',
    activeSubstance: 'Инсулин гларгин',
    group: 'Эндокринологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/insulin-glargine.svg',
    images: ['/assets/img/drugs/packshots/insulin-glargine.svg', '/assets/img/drugs/pack-03.svg'],
  },
  'препарат 22': {
    name: 'Цефовецин',
    activeSubstance: 'Цефовецин',
    group: 'Антибиотик',
    thumbnailUrl: '/assets/img/drugs/packshots/cefovecin.svg',
    images: ['/assets/img/drugs/packshots/cefovecin.svg', '/assets/img/drugs/pack-08.svg'],
  },
  'цефовецин': {
    name: 'Цефовецин',
    activeSubstance: 'Цефовецин',
    group: 'Антибиотик',
    thumbnailUrl: '/assets/img/drugs/packshots/cefovecin.svg',
    images: ['/assets/img/drugs/packshots/cefovecin.svg', '/assets/img/drugs/pack-08.svg'],
  },
  'препарат 23': {
    name: 'Урсодезоксихолевая кислота',
    activeSubstance: 'Урсодезоксихолевая кислота',
    group: 'Гепатопротектор',
    thumbnailUrl: '/assets/img/drugs/packshots/ursodeoxycholic-acid.svg',
    images: ['/assets/img/drugs/packshots/ursodeoxycholic-acid.svg', '/assets/img/drugs/pack-12.svg'],
  },
  'урсодезоксихолевая кислота': {
    name: 'Урсодезоксихолевая кислота',
    activeSubstance: 'Урсодезоксихолевая кислота',
    group: 'Гепатопротектор',
    thumbnailUrl: '/assets/img/drugs/packshots/ursodeoxycholic-acid.svg',
    images: ['/assets/img/drugs/packshots/ursodeoxycholic-acid.svg', '/assets/img/drugs/pack-12.svg'],
  },
  'препарат 24': {
    name: 'Дорзоламид',
    activeSubstance: 'Дорзоламид',
    group: 'Офтальмологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/dorzolamide.svg',
    images: ['/assets/img/drugs/packshots/dorzolamide.svg', '/assets/img/drugs/pack-10.svg'],
  },
  'дорзоламид': {
    name: 'Дорзоламид',
    activeSubstance: 'Дорзоламид',
    group: 'Офтальмологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/dorzolamide.svg',
    images: ['/assets/img/drugs/packshots/dorzolamide.svg', '/assets/img/drugs/pack-10.svg'],
  },
  'препарат 25': {
    name: 'Тразодон',
    activeSubstance: 'Тразодон',
    group: 'Нейромодулятор',
    thumbnailUrl: '/assets/img/drugs/packshots/trazodone.svg',
    images: ['/assets/img/drugs/packshots/trazodone.svg', '/assets/img/drugs/pack-07.svg'],
  },
  'тразодон': {
    name: 'Тразодон',
    activeSubstance: 'Тразодон',
    group: 'Нейромодулятор',
    thumbnailUrl: '/assets/img/drugs/packshots/trazodone.svg',
    images: ['/assets/img/drugs/packshots/trazodone.svg', '/assets/img/drugs/pack-07.svg'],
  },
  'препарат 26': {
    name: 'Фенобарбитал',
    activeSubstance: 'Фенобарбитал',
    group: 'Противосудорожный',
    thumbnailUrl: '/assets/img/drugs/packshots/phenobarbital.svg',
    images: ['/assets/img/drugs/packshots/phenobarbital.svg', '/assets/img/drugs/pack-10.svg'],
  },
  'фенобарбитал': {
    name: 'Фенобарбитал',
    activeSubstance: 'Фенобарбитал',
    group: 'Противосудорожный',
    thumbnailUrl: '/assets/img/drugs/packshots/phenobarbital.svg',
    images: ['/assets/img/drugs/packshots/phenobarbital.svg', '/assets/img/drugs/pack-10.svg'],
  },
  'препарат 27': {
    name: 'Метронидазол',
    activeSubstance: 'Метронидазол',
    group: 'Антибиотик',
    thumbnailUrl: '/assets/img/drugs/packshots/metronidazole.svg',
    images: ['/assets/img/drugs/packshots/metronidazole.svg', '/assets/img/drugs/pack-08.svg'],
  },
  'метронидазол': {
    name: 'Метронидазол',
    activeSubstance: 'Метронидазол',
    group: 'Антибиотик',
    thumbnailUrl: '/assets/img/drugs/packshots/metronidazole.svg',
    images: ['/assets/img/drugs/packshots/metronidazole.svg', '/assets/img/drugs/pack-08.svg'],
  },
  'препарат 28': {
    name: 'Силденафил',
    activeSubstance: 'Силденафил',
    group: 'Кардиологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/sildenafil.svg',
    images: ['/assets/img/drugs/packshots/sildenafil.svg', '/assets/img/drugs/pack-06.svg'],
  },
  'силденафил': {
    name: 'Силденафил',
    activeSubstance: 'Силденафил',
    group: 'Кардиологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/sildenafil.svg',
    images: ['/assets/img/drugs/packshots/sildenafil.svg', '/assets/img/drugs/pack-06.svg'],
  },
  'препарат 29': {
    name: 'Тобрамицин',
    activeSubstance: 'Тобрамицин',
    group: 'Офтальмологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/tobramycin.svg',
    images: ['/assets/img/drugs/packshots/tobramycin.svg', '/assets/img/drugs/pack-12.svg'],
  },
  'тобрамицин': {
    name: 'Тобрамицин',
    activeSubstance: 'Тобрамицин',
    group: 'Офтальмологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/tobramycin.svg',
    images: ['/assets/img/drugs/packshots/tobramycin.svg', '/assets/img/drugs/pack-12.svg'],
  },
  'препарат 30': {
    name: 'Атенолол',
    activeSubstance: 'Атенолол',
    group: 'Кардиологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/atenolol.svg',
    images: ['/assets/img/drugs/packshots/atenolol.svg', '/assets/img/drugs/pack-11.svg'],
  },
  'атенолол': {
    name: 'Атенолол',
    activeSubstance: 'Атенолол',
    group: 'Кардиологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/atenolol.svg',
    images: ['/assets/img/drugs/packshots/atenolol.svg', '/assets/img/drugs/pack-11.svg'],
  },
  'препарат 31': {
    name: 'Спиронолактон',
    activeSubstance: 'Спиронолактон',
    group: 'Диуретик',
    thumbnailUrl: '/assets/img/drugs/packshots/spironolactone.svg',
    images: ['/assets/img/drugs/packshots/spironolactone.svg', '/assets/img/drugs/pack-05.svg'],
  },
  'спиронолактон': {
    name: 'Спиронолактон',
    activeSubstance: 'Спиронолактон',
    group: 'Диуретик',
    thumbnailUrl: '/assets/img/drugs/packshots/spironolactone.svg',
    images: ['/assets/img/drugs/packshots/spironolactone.svg', '/assets/img/drugs/pack-05.svg'],
  },
  'препарат 32': {
    name: 'Циклоспорин',
    activeSubstance: 'Циклоспорин',
    group: 'Дерматологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/cyclosporine.svg',
    images: ['/assets/img/drugs/packshots/cyclosporine.svg', '/assets/img/drugs/pack-03.svg'],
  },
  'циклоспорин': {
    name: 'Циклоспорин',
    activeSubstance: 'Циклоспорин',
    group: 'Дерматологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/cyclosporine.svg',
    images: ['/assets/img/drugs/packshots/cyclosporine.svg', '/assets/img/drugs/pack-03.svg'],
  },
  'препарат 33': {
    name: 'Оклацитиниб',
    activeSubstance: 'Оклацитиниб',
    group: 'Дерматологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/oclacitinib.svg',
    images: ['/assets/img/drugs/packshots/oclacitinib.svg', '/assets/img/drugs/pack-04.svg'],
  },
  'оклацитиниб': {
    name: 'Оклацитиниб',
    activeSubstance: 'Оклацитиниб',
    group: 'Дерматологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/oclacitinib.svg',
    images: ['/assets/img/drugs/packshots/oclacitinib.svg', '/assets/img/drugs/pack-04.svg'],
  },
  'препарат 34': {
    name: 'Селамектин',
    activeSubstance: 'Селамектин',
    group: 'Антипаразитарный препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/selamectin.svg',
    images: ['/assets/img/drugs/packshots/selamectin.svg', '/assets/img/drugs/pack-02.svg'],
  },
  'селамектин': {
    name: 'Селамектин',
    activeSubstance: 'Селамектин',
    group: 'Антипаразитарный препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/selamectin.svg',
    images: ['/assets/img/drugs/packshots/selamectin.svg', '/assets/img/drugs/pack-02.svg'],
  },
  'препарат 35': {
    name: 'Флуконазол',
    activeSubstance: 'Флуконазол',
    group: 'Противогрибковый препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/fluconazole.svg',
    images: ['/assets/img/drugs/packshots/fluconazole.svg', '/assets/img/drugs/pack-08.svg'],
  },
  'флуконазол': {
    name: 'Флуконазол',
    activeSubstance: 'Флуконазол',
    group: 'Противогрибковый препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/fluconazole.svg',
    images: ['/assets/img/drugs/packshots/fluconazole.svg', '/assets/img/drugs/pack-08.svg'],
  },
  'препарат 36': {
    name: 'Левотироксин',
    activeSubstance: 'Левотироксин',
    group: 'Эндокринологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/levothyroxine.svg',
    images: ['/assets/img/drugs/packshots/levothyroxine.svg', '/assets/img/drugs/pack-09.svg'],
  },
  'левотироксин': {
    name: 'Левотироксин',
    activeSubstance: 'Левотироксин',
    group: 'Эндокринологический препарат',
    thumbnailUrl: '/assets/img/drugs/packshots/levothyroxine.svg',
    images: ['/assets/img/drugs/packshots/levothyroxine.svg', '/assets/img/drugs/pack-09.svg'],
  },
};

function normalize(value) {
  return String(value || '').trim().toLowerCase();
}

export function getDrugPresentation(drug) {
  if (!drug || typeof drug !== 'object') {
    return {
      name: '',
      activeSubstance: '',
      group: '',
      thumbnailUrl: '/assets/img/drugs/pack-01.svg',
      images: ['/assets/img/drugs/pack-01.svg'],
    };
  }

  const rawName = normalize(drug.name);
  const rawActiveSubstance = normalize(drug.active_substance);
  const curated = CURATED_DRUGS[rawName] || CURATED_DRUGS[rawActiveSubstance];

  return {
    name: curated?.name || drug.name || '',
    activeSubstance: curated?.activeSubstance || drug.active_substance || '',
    group: curated?.group || drug.group || '',
    thumbnailUrl: curated?.thumbnailUrl || drug.thumbnail_url || '/assets/img/drugs/pack-01.svg',
    images: curated?.images || drug.images || [drug.thumbnail_url || '/assets/img/drugs/pack-01.svg'],
  };
}
